networks:
  direct_net:
    external: true
  internal:
    external: false

services:
  job:
    build: .
    container_name: job
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; gunicorn --bind 0.0.0.0:8000 config.wsgi;'
    volumes:
      - .:/home/user/web
    restart: always
    ports:
      - '3008:8000'
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.job-rtr.entrypoints=https"
      - "traefik.http.routers.job-rtr.rule=Host(`$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.job-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.job-rtr.service=job-svc"
      - "traefik.http.services.job-svc.loadbalancer.server.port=8000"
      ## Disable from watchtower
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - direct_net
      - internal

  bot:
    build: .
    container_name: bot
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python3 manage.py bot'
    volumes:
      - .:/home/user/web
    restart: always
    networks:
      - direct_net
      - internal
    labels:
      ## Disable from watchtower
      - "com.centurylinklabs.watchtower.enable=false"

  redis:
    container_name: redis
    image: redis
    restart: always
    networks:
      - direct_net
      - internal

  worker:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/home/user/web
    command: bash -c 'celery -A config worker --loglevel=info'
    networks:
      - direct_net
      - internal
    labels:
      ## Disable from watchtower
      - "com.centurylinklabs.watchtower.enable=false"

  celery-beats:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/home/user/web
    command: bash -c 'celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler'
    networks:
      - direct_net
      - internal
    labels:
      ## Disable from watchtower
      - "com.centurylinklabs.watchtower.enable=false"

  flower:
    build:
      context: .
      dockerfile: flower.Dockerfile
    command: bash -c 'celery -A config flower'
    volumes:
      - .:/home/user/web
    working_dir: /data
    ports:
      - '5555:5555'
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - worker
      - redis
    networks:
      - direct_net
      - internal
    labels:
      ## Disable from watchtower
      - "com.centurylinklabs.watchtower.enable=false"
