# Generated by Django 4.0.2 on 2022-02-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID вакансии')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название вакансии')),
                ('company', models.CharField(db_index=True, max_length=255, verbose_name='Название компании')),
                ('url_company', models.URLField(verbose_name='Ссылка на компанию')),
                ('url_vacancy', models.URLField(verbose_name='Ссылка на вакансию')),
                ('status', models.CharField(choices=[('new', 'активно'), ('archive', 'в архиве'), ('unavailable', 'недоступна')], max_length=150, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(verbose_name='Дата размещения')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
