# Generated by Django 4.0.2 on 2022-02-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_area_alter_vacancy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='parent_id',
            field=models.PositiveIntegerField(verbose_name='parent_id area'),
        ),
    ]
