# Generated by Django 4.0.2 on 2022-02-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_area_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='parent_id',
            field=models.IntegerField(verbose_name='parent_id area'),
        ),
    ]
