# Generated by Django 4.0.2 on 2022-02-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_area_in_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(db_index=True, max_length=255, verbose_name='Текст запроса')),
                ('in_search', models.BooleanField(default=False, verbose_name='Искать?')),
            ],
            options={
                'verbose_name': 'Поисковой запрос',
                'verbose_name_plural': 'Поисковые запросы',
            },
        ),
    ]
