# Generated by Django 3.2.11 on 2022-04-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_searchquery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='url_vacancy',
            new_name='alternate_url',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='company',
            new_name='employer_name',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='url_company',
            new_name='employer_url',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание вакансии'),
        ),
    ]
