# Generated by Django 3.2.11 on 2024-12-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_vacancy_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('new', 'активно'), ('archive', 'в архиве'), ('unavailable', 'недоступна'), ('not_found', 'не найдено')], default='new', max_length=150, verbose_name='Статус'),
        ),
    ]
