# Generated by Django 3.2.11 on 2025-01-29 04:16

from django.db import migrations, models

from core.enums import VacancyStatus


def upgrade_status_vacancy(apps, schema_editor):
    vacancies = apps.get_model('core', 'Vacancy')
    statuses = {
        'new': VacancyStatus.new.value,
        'archive': VacancyStatus.archive.value,
        'unavailable': VacancyStatus.unavailable.value,
        'not_found': VacancyStatus.not_found.value,
    }
    for vacancy in vacancies.objects.all():
        vacancy.status_tmp = statuses[vacancy.status]
        vacancy.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_vacancy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='status_tmp',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'активно'), (2, 'в архиве'), (3, 'недоступна'), (4, 'не найдено')], default=1,
                verbose_name='Статус'),
        ),
        migrations.RunPython(upgrade_status_vacancy, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='vacancy',
            name='status',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='status_tmp',
            new_name='status',
        ),
    ]
